#  Copyright (c) 2026 Texas Instruments Incorporated
#  SPDX-License-Identifier: Apache-2.0

# Renders the generic linker description into a TI .cmd, as armlink does for a scatter file.

cmake_minimum_required(VERSION 3.20)

set(IND "    ")

#  TI has no SORT_BY_NAME. A priority wildcard therefore has to be expanded
#  into an explicitly ordered sequence, widest priority last.
function(c7x_expand_input pattern sort out_var)
  set(result "${pattern}")
  if(sort AND "${pattern}" MATCHES "^(.*_P_)(\\?\\?+)(_.*)$")
    set(head "${CMAKE_MATCH_1}")
    set(tail "${CMAKE_MATCH_3}")
    string(LENGTH "${CMAKE_MATCH_2}" qcount)
    math(EXPR rest "${qcount} - 1")
    string(REPEAT "?" ${rest} suffix)
    set(result)
    foreach(digit RANGE 0 9)
      list(APPEND result "${head}${digit}${suffix}${tail}")
    endforeach()
  endif()
  set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(c7x_attr_key name out_var)
  string(REGEX REPLACE "^\\." "" key "${name}")
  string(REGEX REPLACE "[^A-Za-z0-9]" "_" key "${key}")
  set(${out_var} "${key}" PARENT_SCOPE)
endfunction()

function(section_to_string)
  cmake_parse_arguments(STRING "" "SECTION;STRING" "" ${ARGN})

  get_property(name     GLOBAL PROPERTY ${STRING_SECTION}_NAME)
  get_property(align    GLOBAL PROPERTY ${STRING_SECTION}_ALIGN)
  get_property(type     GLOBAL PROPERTY ${STRING_SECTION}_TYPE)
  get_property(noinit   GLOBAL PROPERTY ${STRING_SECTION}_NOINIT)
  get_property(noinput  GLOBAL PROPERTY ${STRING_SECTION}_NOINPUT)
  get_property(min_size GLOBAL PROPERTY ${STRING_SECTION}_MIN_SIZE)
  get_property(indicies GLOBAL PROPERTY ${STRING_SECTION}_SETTINGS_INDICIES)

  get_parent(OBJECT ${STRING_SECTION} PARENT region TYPE REGION)
  get_property(region_name GLOBAL PROPERTY ${region}_NAME)

  #  A member of a TI GROUP is placed by the group, so it carries no
  #  allocation of its own.
  get_property(parent GLOBAL PROPERTY ${STRING_SECTION}_PARENT)
  get_property(parent_name GLOBAL PROPERTY ${parent}_NAME)
  set(c7x_grouped FALSE)
  if("${parent_name}" IN_LIST C7X_CMD_GROUPS)
    set(c7x_grouped TRUE)
  endif()

  set(c7x_props)
  if("${type}" STREQUAL "NOLOAD" OR "${type}" STREQUAL "BSS")
    set(c7x_props "type=NOLOAD")
  elseif(noinit)
    set(c7x_props "type=NOINIT")
  endif()

  set(c7x_contents)
  foreach(idx ${indicies})
    get_property(input   GLOBAL PROPERTY ${STRING_SECTION}_SETTING_${idx}_INPUT)
    get_property(symbols GLOBAL PROPERTY ${STRING_SECTION}_SETTING_${idx}_SYMBOLS)
    get_property(sort    GLOBAL PROPERTY ${STRING_SECTION}_SETTING_${idx}_SORT)
    get_property(keep    GLOBAL PROPERTY ${STRING_SECTION}_SETTING_${idx}_KEEP)

    set(sym_start)
    set(sym_end)
    list(LENGTH symbols symbol_count)
    if(symbol_count GREATER 0)
      list(GET symbols 0 sym_start)
    endif()
    if(symbol_count GREATER 1)
      list(GET symbols 1 sym_end)
    endif()

    if(sym_start)
      string(APPEND c7x_contents "${IND}${IND}${sym_start} = .;\n")
    endif()
    foreach(pattern ${input})
      #  TI has no KEEP(); an input nothing references survives only by --retain.
      if(keep)
        set_property(GLOBAL APPEND PROPERTY C7X_CMD_KEEP "*(${pattern})")
      endif()
      c7x_expand_input("${pattern}" "${sort}" expanded)
      foreach(one ${expanded})
        string(APPEND c7x_contents "${IND}${IND}*(${one})\n")
      endforeach()
    endforeach()
    if(sym_end)
      string(APPEND c7x_contents "${IND}${IND}${sym_end} = .;\n")
    endif()
  endforeach()

  if(min_size)
    string(APPEND c7x_contents "${IND}${IND}. += ${min_size};\n")
  endif()

  set(c7x_head "${IND}${name}")
  if(c7x_grouped)
    set(c7x_head "${IND}${IND}${name}")
  endif()
  if(c7x_props)
    string(APPEND c7x_head " : ${c7x_props}")
  endif()

  set(c7x_tail)
  if(NOT c7x_grouped)
    set(c7x_tail " > ${region_name}")
    if(align)
      string(APPEND c7x_tail " ALIGN(${align})")
    endif()
    c7x_attr_key("${name}" attr_key)
    if(DEFINED C7X_TI_ATTR_${attr_key})
      string(APPEND c7x_tail " ${C7X_TI_ATTR_${attr_key}}")
    endif()
  endif()

  #  An unbraced placement is TI's default gathering of <name> and <name>.*.
  if(c7x_contents OR (noinput AND NOT c7x_grouped))
    set(c7x_stmt "${c7x_head}${c7x_tail}\n${IND}{\n${c7x_contents}${IND}}\n")
  else()
    set(c7x_stmt "${c7x_head}${c7x_tail}\n")
  endif()

  set(${STRING_STRING} "${${STRING_STRING}}${c7x_stmt}" PARENT_SCOPE)
endfunction()

#  A TI GROUP keeps its members contiguous and in order; it is the only
#  construct here that nests, so only groups named in C7X_CMD_GROUPS get one.
function(group_to_string)
  cmake_parse_arguments(STRING "" "OBJECT;STRING" "" ${ARGN})

  get_property(type GLOBAL PROPERTY ${STRING_OBJECT}_OBJ_TYPE)
  get_property(name GLOBAL PROPERTY ${STRING_OBJECT}_NAME)

  set(wrap FALSE)
  if("${type}" STREQUAL "GROUP" AND "${name}" IN_LIST C7X_CMD_GROUPS)
    set(wrap TRUE)
    get_parent(OBJECT ${STRING_OBJECT} PARENT region TYPE REGION)
    get_property(region_name GLOBAL PROPERTY ${region}_NAME)
    set(${STRING_STRING} "${${STRING_STRING}}${IND}GROUP: > ${region_name}\n${IND}{\n")
  endif()

  get_property(sections GLOBAL PROPERTY ${STRING_OBJECT}_SECTIONS_FIXED)
  foreach(section ${sections})
    to_string(OBJECT ${section} STRING ${STRING_STRING})
  endforeach()

  get_property(groups GLOBAL PROPERTY ${STRING_OBJECT}_GROUPS)
  foreach(group ${groups})
    to_string(OBJECT ${group} STRING ${STRING_STRING})
  endforeach()

  get_property(sections GLOBAL PROPERTY ${STRING_OBJECT}_SECTIONS)
  foreach(section ${sections})
    to_string(OBJECT ${section} STRING ${STRING_STRING})
  endforeach()

  get_parent(OBJECT ${STRING_OBJECT} PARENT parent TYPE SYSTEM)
  get_property(regions GLOBAL PROPERTY ${parent}_REGIONS)
  list(REMOVE_ITEM regions ${STRING_OBJECT})
  foreach(region ${regions})
    get_property(vma GLOBAL PROPERTY ${region}_NAME)
    foreach(kind SECTIONS_FIXED GROUPS SECTIONS)
      get_property(items GLOBAL PROPERTY ${STRING_OBJECT}_${vma}_${kind})
      foreach(item ${items})
        to_string(OBJECT ${item} STRING ${STRING_STRING})
      endforeach()
    endforeach()
  endforeach()

  get_property(symbols GLOBAL PROPERTY ${STRING_OBJECT}_SYMBOLS)
  foreach(symbol ${symbols})
    to_string(OBJECT ${symbol} STRING ${STRING_STRING})
  endforeach()

  if(wrap)
    set(${STRING_STRING} "${${STRING_STRING}}${IND}}\n")
  endif()
  set(${STRING_STRING} ${${STRING_STRING}} PARENT_SCOPE)
endfunction()

function(symbol_to_string)
  cmake_parse_arguments(STRING "" "SYMBOL;STRING" "" ${ARGN})

  get_property(symbol GLOBAL PROPERTY ${STRING_SYMBOL}_SYMBOL)
  get_property(expr   GLOBAL PROPERTY ${STRING_SYMBOL}_EXPR)

  string(REPLACE "\\" "" expr "${expr}")
  string(REGEX MATCHALL "@([^@]*)@" match_res "${expr}")
  foreach(match ${match_res})
    string(REPLACE "@" "" match ${match})
    string(REPLACE "@${match}@" "${match}" expr "${expr}")
  endforeach()

  set(${STRING_STRING} "${${STRING_STRING}}${symbol} = ${expr};\n" PARENT_SCOPE)
endfunction()

function(c7x_options_to_string entry out_var)
  set(text)
  if(DEFINED C7X_CMD_HEAP)
    string(APPEND text "-heap  ${C7X_CMD_HEAP}\n")
  endif()
  if(DEFINED C7X_CMD_STACK)
    string(APPEND text "-stack ${C7X_CMD_STACK}\n")
  endif()
  separate_arguments(suppress UNIX_COMMAND "${C7X_CMD_DIAG_SUPPRESS}")
  foreach(code ${suppress})
    string(APPEND text "--diag_suppress=${code}\n")
  endforeach()
  if(entry)
    string(APPEND text "-e ${entry}\n")
  endif()
  separate_arguments(retain UNIX_COMMAND "${C7X_CMD_RETAIN}")
  get_property(keep GLOBAL PROPERTY C7X_CMD_KEEP)
  list(APPEND retain ${keep})
  list(REMOVE_DUPLICATES retain)
  if(retain)
    string(APPEND text "\n")
    foreach(pattern ${retain})
      string(APPEND text "--retain=\"${pattern}\"\n")
    endforeach()
  endif()
  set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

function(system_to_string)
  cmake_parse_arguments(STRING "" "OBJECT;STRING" "" ${ARGN})

  get_property(regions GLOBAL PROPERTY ${STRING_OBJECT}_REGIONS)
  get_property(entry   GLOBAL PROPERTY ${STRING_OBJECT}_ENTRY)
  get_property(symbols GLOBAL PROPERTY ${STRING_OBJECT}_SYMBOLS)

  set(out "/*  Generated by cmake/linker/cl7x/cmd_script.cmake from\n")
  string(APPEND out " *  cmake/linker_script/c7x/linker.cmake. Do not edit. */\n\n")

  set(c7x_regions_out "MEMORY\n{\n")

  foreach(region ${regions})
    get_property(name    GLOBAL PROPERTY ${region}_NAME)
    get_property(address GLOBAL PROPERTY ${region}_ADDRESS)
    get_property(size    GLOBAL PROPERTY ${region}_SIZE)
    get_property(flags   GLOBAL PROPERTY ${region}_FLAGS)
    string(TOUPPER "${flags}" flags)
    if(flags)
      set(flags " (${flags})")
    endif()
    string(APPEND c7x_regions_out "${IND}${name}${flags}: org = ${address}, len = ${size}\n")
  endforeach()
  string(APPEND c7x_regions_out "}\n\nSECTIONS\n{\n")

  set(c7x_sections_out)
  foreach(region ${regions})
    get_property(empty GLOBAL PROPERTY ${region}_EMPTY)
    if(NOT empty)
      to_string(OBJECT ${region} STRING c7x_sections_out)
    endif()
  endforeach()
  #  Sections first: rendering them collects the KEEP inputs the options retain.
  c7x_options_to_string("${entry}" options)
  string(APPEND out "${options}\n${c7x_regions_out}${c7x_sections_out}}\n")

  foreach(symbol ${symbols})
    string(APPEND out "\n")
    to_string(OBJECT ${symbol} STRING out)
  endforeach()

  set(${STRING_STRING} "${${STRING_STRING}}${out}" PARENT_SCOPE)
endfunction()

include(${CMAKE_CURRENT_LIST_DIR}/../linker_script_common.cmake)
