#!/usr/bin/env python3
"""Emit regtest.asm -- a per-register preservation test for the C7x ISR path.

Fills every architecturally-saved register with a distinct pattern, spins until
an interrupt has been taken, then dumps them all for the C side to compare.
Generated rather than hand-written: it is ~400 near-identical sequences and a
typo in one of them silently weakens the test instead of failing it.

Three facts constrain the register assignment, all verified by assembling:

  * B_n is the low 64 bits of VB_n. Patterning both makes B's write clobber
    VB and report a false failure, so only VB is patterned -- that covers B.
  * Predication is A-file and only A0-A5 ([!A6] and up are rejected, E0003),
    so each spin loop costs one low-A register as its predicate.
  * VBL reads on .S2 and VBM reads on .M2; the other unit is rejected.

CUCR is control state, not data -- round-tripped (read before, read after,
compare) rather than written with a pattern.

Two passes cover the harness registers of the other:
  pass 1  harness D0/D1/D2 + predicate A5  -> everything except A5, D0-D2
  pass 2  harness A4/A6/A7 + predicate A0  -> D0-D14 and A5
"""
import sys

OFF_A, OFF_D, OFF_P = 0x000, 0x080, 0x180
OFF_VB, OFF_VBL, OFF_VBM, OFF_CUCR = 0xA00, 0x400, 0x500, 0x600
OFF_SAVE = 0x700                      # callee-saved spill, not compared
OFF_AL, OFF_AM = 0xC00, 0xC80
OFF_CTL, OFF_CTL2 = 0xD00, 0xD20      # FPCR/FSR/GPLY/GFPGFR pre and post
CTLREGS = ["FPCR", "FSR", "GPLY", "GFPGFR"]

P1_PAT, P1_FLAG, P1_OUT, P1_PRED = "D0", "D1", "D2", "A5"
P1_A = [i for i in range(16) if i != 5]
P1_D = list(range(3, 15))             # D15 is SP
# args arrive in A4/A5/A6, so out must be copied off A5 before A5 is patterned;
# A7 is not an argument register and A0-A5 is the only legal predicate range.
P2_PAT, P2_OUT, P2_FLAG, P2_PRED = "A4", "A7", "A6", "A0"
P2_D = list(range(15))
P2_A = [5]

L = []
def e(s=""):
    L.append(s)

def spin(label, flag, pred):
    e(f"{label}:")
    e(f"        LDW     .D1     *{flag}(0), {pred}")
    e("        NOP     5")
    e(f" [!{pred}]  B       .B1     {label}")
    e("        NOP     5")

e(";  Copyright (c) 2026 Texas Instruments Incorporated")
e(";  SPDX-License-Identifier: Apache-2.0")
e(";")
e("; GENERATED by tests/arch/c7x/core/gen_regtest_asm.py -- do not edit by hand.")
e()
e("        .global c7x_regtest_isr")
e("        .global c7x_regtest_dfile")
e("        .global c7x_regtest_switch")
e()

# ------------------------------------------------------------------ pass 1
e("        .sect \".text:c7x_regtest_isr\"")
e("        .asmfunc")
e("c7x_regtest_isr:")
e(f"        MV      .D1     A4, {P1_PAT}")
e(f"        MV      .D1     A5, {P1_OUT}")
e(f"        MV      .D1     A6, {P1_FLAG}")
e("        NOP     5")

e("; spill callee-saved state into the out buffer's reserved tail")
for i in range(8, 16):
    e(f"        STD     .D1     A{i}, *{P1_OUT}({OFF_SAVE + (i - 8) * 8})")
e("        MVC     .S1     RP, A1")
e("        NOP     5")
e(f"        STD     .D1     A1, *{P1_OUT}({OFF_SAVE + 0x40})")
e(f"        VST4D   .D2     VB14, *{P1_OUT}({OFF_SAVE + 0x60})")
e(f"        VST4D   .D2     VB15, *{P1_OUT}({OFF_SAVE + 0x80})")

e("; CUCR is control state: record it rather than overwrite it")
for i in range(8):
    e(f"        MVC     .C2     CUCR{i}, VB0")
    e("        NOP     5")
    e(f"        VST4D   .D2     VB0, *{P1_PAT}({OFF_CUCR + i * 32})")

e("; FPCR/FSR/GPLY/GFPGFR are control state: round-tripped pre vs post")
for i, r in enumerate(CTLREGS):
    e(f"        MVC     .S1     {r}, A0")
    e("        NOP     3")
    e(f"        STD     .D1     A0, *{P1_OUT}({OFF_CTL + i * 8})")

e("; VBL/VBM stage through VB0, so fill them before VB is patterned")
for i in range(8):
    e(f"        VLD4D   .D1     *{P1_PAT}({OFF_VBL + i * 32}), VB0")
    e("        NOP     5")
    e(f"        VMV     .M2     VB0, VBL{i}")
for i in range(8):
    e(f"        VLD4D   .D1     *{P1_PAT}({OFF_VBM + i * 32}), VB0")
    e("        NOP     5")
    e(f"        VMV     .M2     VB0, VBM{i}")

e("; P stages through B0, which aliases VB0 -- also before the VB fill")
for i in range(8):
    e(f"        LDD     .D1     *{P1_PAT}({OFF_P + i * 8}), B0")
    e("        NOP     5")
    e(f"        MV      .L2     B0, P{i}")

e("; VB0-VB15, which covers B0-B15")
for i in range(16):
    e(f"        VLD4D   .D1     *{P1_PAT}({OFF_VB + i * 32}), VB{i}")
e("        NOP     5")

for i in P1_D:
    e(f"        LDD     .D1     *{P1_PAT}({OFF_D + i * 8}), D{i}")
e("        NOP     5")

e("; AL/AM stage through A0/A1, so before the A file is patterned")
for i in range(16):
    e(f"        LDD     .D1     *{P1_PAT}({OFF_AL + i * 8}), A0")
    e("        NOP     5")
    e(f"        MV      .L1     A0, AL{i}")
for i in range(16):
    e(f"        LDD     .D1     *{P1_PAT}({OFF_AM + i * 8}), A0")
    e("        NOP     5")
    e(f"        MV      .M1     A0, AM{i}")

e("; A last -- A4/A5/A6 held the arguments until now")
for i in P1_A:
    e(f"        LDD     .D1     *{P1_PAT}({OFF_A + i * 8}), A{i}")
e("        NOP     5")

e("; wait for an interrupt; the loop touches only harness registers")
spin("c7x_regtest_spin", P1_FLAG, P1_PRED)

e("; dump VB before anything that stages through VB0/B0")
for i in P1_A:
    e(f"        STD     .D1     A{i}, *{P1_OUT}({OFF_A + i * 8})")
for i in P1_D:
    e(f"        STD     .D1     D{i}, *{P1_OUT}({OFF_D + i * 8})")
for i in range(16):
    e(f"        VST4D   .D2     VB{i}, *{P1_OUT}({OFF_VB + i * 32})")
for i in range(8):
    e(f"        VMV     .S2     VBL{i}, VB0")
    e("        NOP     5")
    e(f"        VST4D   .D2     VB0, *{P1_OUT}({OFF_VBL + i * 32})")
for i in range(8):
    e(f"        VMV     .M2     VBM{i}, VB0")
    e("        NOP     5")
    e(f"        VST4D   .D2     VB0, *{P1_OUT}({OFF_VBM + i * 32})")
for i in range(8):
    e(f"        MVPB    .L2     P{i}, B0")
    e("        NOP     5")
    e(f"        STD     .D2     B0, *{P1_OUT}({OFF_P + i * 8})")
for i in range(8):
    e(f"        MVC     .C2     CUCR{i}, VB0")
    e("        NOP     5")
    e(f"        VST4D   .D2     VB0, *{P1_OUT}({OFF_CUCR + i * 32})")

e("; AL/AM after the A dump has freed A0")
for i in range(16):
    e(f"        MV      .L1     AL{i}, A0")
    e("        NOP     3")
    e(f"        STD     .D1     A0, *{P1_OUT}({OFF_AL + i * 8})")
for i in range(16):
    e(f"        MV      .M1     AM{i}, A0")
    e("        NOP     3")
    e(f"        STD     .D1     A0, *{P1_OUT}({OFF_AM + i * 8})")
for i, r in enumerate(CTLREGS):
    e(f"        MVC     .S1     {r}, A0")
    e("        NOP     3")
    e(f"        STD     .D1     A0, *{P1_OUT}({OFF_CTL2 + i * 8})")

for i in range(8, 16):
    e(f"        LDD     .D1     *{P1_OUT}({OFF_SAVE + (i - 8) * 8}), A{i}")
e(f"        LDD     .D1     *{P1_OUT}({OFF_SAVE + 0x40}), A1")
e(f"        VLD4D   .D1     *{P1_OUT}({OFF_SAVE + 0x60}), VB14")
e(f"        VLD4D   .D1     *{P1_OUT}({OFF_SAVE + 0x80}), VB15")
e("        NOP     5")
e("        MVC     .S1     A1, RP")
e("        NOP     5")
e("        RET     .B1")
e("        NOP     5")
e("        .endasmfunc")
e()

# ------------------------------------------------------------------ pass 2
e("        .sect \".text:c7x_regtest_dfile\"")
e("        .asmfunc")
e("c7x_regtest_dfile:")
e(f"        MV      .D1     A5, {P2_OUT}")   # out off A5 before A5 is patterned
e("        NOP     5")
for i in P2_D:
    e(f"        LDD     .D1     *{P2_PAT}({OFF_D + i * 8}), D{i}")
for i in P2_A:
    e(f"        LDD     .D1     *{P2_PAT}({OFF_A + i * 8}), A{i}")
e("        NOP     5")
spin("c7x_regtest_dspin", P2_FLAG, P2_PRED)
for i in P2_D:
    e(f"        STD     .D1     D{i}, *{P2_OUT}({OFF_D + i * 8})")
for i in P2_A:
    e(f"        STD     .D1     A{i}, *{P2_OUT}({OFF_A + i * 8})")
e("        NOP     5")
e("        RET     .B1")
e("        NOP     5")
e("        .endasmfunc")

# ------------------------------------------------------------- context switch
# Only the callee-saved set is asserted here. A context switch is a function
# call, so caller-saved registers are not required to survive one, and TI's own
# TaskSupport_swap saves exactly this set -- including B14/B15 as 64-bit STDs,
# not the full VB14/VB15.
OFF_SW = 0x800
e()
e("        .sect \".text:c7x_regtest_switch\"")
e("        .asmfunc")
e("; SP+0 is ABI-reserved for a callee's return address, so this frame keeps everything")
e("; above it")
e("c7x_regtest_switch:")
e("        ADDD    .D2     D15, -192, D15")
e("        STD     .D1     A5, *D15(112)")
e("        STD     .D1     A6, *D15(120)")
e("        MVC     .S1     RP, A1")
e("        NOP     5")
e("        STD     .D1     A1, *D15(128)")
e("; this routine clobbers the callee-saved set on purpose, so spill it first")
for i in range(8, 16):
    e(f"        STD     .D1     A{i}, *D15({32 + (i - 8) * 8})")
e("        STD     .D1X    B14, *D15(96)")
e("        STD     .D2     B15, *D15(104)")
for i in range(8, 16):
    e(f"        LDD     .D1     *A4({OFF_A + i * 8}), A{i}")
e(f"        LDD     .D1     *A4({OFF_SW + 0x40}), B14")
e(f"        LDD     .D1     *A4({OFF_SW + 0x48}), B15")
e("        NOP     5")
e("        LDD     .D1     *D15(120), A6")
e("        NOP     5")
e("        CALLA   .S1     A6")
e("        NOP     5")
e("        LDD     .D1     *D15(112), A5")
e("        NOP     5")
e("        STD     .D1     A5, *D15(136)")   # what the reload actually produced
for i in range(8, 16):
    e(f"        STD     .D1     A{i}, *A5({OFF_A + i * 8})")
e(f"        STD     .D1X    B14, *A5({OFF_SW + 0x40})")
e(f"        STD     .D1X    B15, *A5({OFF_SW + 0x48})")
for i in range(8, 16):
    e(f"        LDD     .D1     *D15({32 + (i - 8) * 8}), A{i}")
e("        LDD     .D1     *D15(96), B14")
e("        LDD     .D2     *D15(104), B15")
e("        LDD     .D1     *D15(128), A1")
e("        NOP     5")
e("        MVC     .S1     A1, RP")
e("        LDD     .D1     *D15(136), A4")   # returned so C can see it
e("        NOP     5")
e("        ADDD    .D2     D15, 192, D15")
e("        NOP     5")
e("        RET     .B1")
e("        NOP     5")
e("        .endasmfunc")

open(sys.argv[1], "w").write("\n".join(L) + "\n")
print(f"wrote {sys.argv[1]}: {len(L)} lines")
